#!/usr/bin/bash
analyze -f vhdl -lib WORK ../src/pkg.vhd
analyze -f vhdl -lib WORK ../src/control.vhd
analyze -f vhdl -lib WORK ../src/reg8.vhd
analyze -f vhdl -lib WORK ../src/full_FIR.vhd
analyze -f vhdl -lib WORK ../src/my_fir.vhd
#Before completing the reading of source we set one parameter to preserve rtl names in the netlist to ease the procedure for power consumption estimation.
set power_preserve_rtl_hier_names true
#Launch elaborate command to load the components
#elaborate <top entity name> -arch <architecture name> -lib WORK > ./elaborate.txt
elaborate full_FIR -arch struct -lib WORK > ./elaborate.txt
#uniquify #optional command to addres to only 1 specific architecture
link

#*******  Applying constraints   ***************
#create 100 Mhz clock
create_clock -name MY_CLK -period 10 CLK  
set_dont_touch_network MY_CLK

#jitter simulation
set_clock_uncertainty 0.07 [get_clocks MY_CLK]

#input/output delay
set_input_delay 0.5 -max -clock MY_CLK [remove_from_collection [all_inputs] CLK]
set_output_delay 0.5 -max -clock MY_CLK [all_outputs]

#set output load (buffer x4 used)
set OLOAD [load_of NangateOpenCellLibrary/BUF_X4/A]
set_load $OLOAD [all_outputs]

#*********    Start the syntesis    *************
compile >  ./analysis_results/compilation_results.txt

#*********    Save the results      *************
report_timing  >  ./analysis_results/timing_results.txt
report_area    >  ./analysis_results/area_results.txt

#Finally, we can save the data required to complete the design and to perform switchingactivity-based power estimation. 
#First, we ungroup the cells to flatten the hierarchy as follows:
ungroup -all -flatten
#Then, we have to export the netlist in verilog. So that we impose verilog rules for the names of the internal signals. This is obtained with
change_names -hierarchy -rules verilog
#We also save a file describing the delay of the netlist:
write_sdf ../netlist/myfir.sdf
#We can now save the netlist in verilog:
write -f verilog -hierarchy -output ../netlist/myfir.v
#and the constraints to the input and output ports in a standard format:
write_sdc ../netlist/myfir.sdc


#******* close Design compiler    ****************
quit
